### ISSUE TITLE
django.db.utils.OperationalError: duplicate column name: department_id

### ISSUE THREAD

**Issue by TSmiley12** [adilmohak/django-lms#1]
\Online Examination\New folder\django-lms-main\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: duplicate column name: department_id

**Comment by Tayy3bkh4n** [comment]
Hi,
I am very to Django; I am trying to find the setting.py file but can't find it.  After cloning, the LMS gets the following error.  Please tell me how I can resolve these issues.  I appreciate any help you can provide.

**Comment by adilmohak** [comment]
Hi there,

Could you elaborate more on that please, is this error occurring when
running `python manage.py migrate`? Also, have you cloned the latest
version, because I pushed changes like 4 days ago?

Basically, the error is reporting that the column `department_id` is
already been created and you're trying to re-create it, which is not
possible. You could solve this by dropping/deleting your database and
re-run `python manage.py makemigrations` and `python manage.py migrate`
respectively.

Let me know for further help

Best regards
Adil Mohammed
